# For security reasons this is a separate GitHub workflow, see https://github.com/google/gson/issues/2429#issuecomment-1622522842
# Once https://github.com/mojohaus/animal-sniffer/issues/252 or https://github.com/mojohaus/animal-sniffer/pull/253
# are resolved, can consider adjusting pom.xml to include this as part of normal Maven build

name: Check Android compatibility

on: [push, pull_request]

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  check-android-compatibility:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6

      - name: Set up JDK 11
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9  # v4.2.1
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Check Android compatibility
        run: |
          # Run 'test' phase because plugin normally expects to be executed after tests have been compiled
          # Have to skip 'test-jpms' module because it requires that full Gson JAR has been built
          mvn --batch-mode --no-transfer-progress test animal-sniffer:check@check-android-compatibility -DskipTests --projects '!test-jpms'
